# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0bf3aabcac8770d081812b37e2d0c0e7a6d6f8a3bdfbec4253ab971d98b52386c616d7658320420b113c059f433e8311aaa67ec45839cc245ff1fd9edf6a412

test:
  secret_key_base: a58a89cc7cd8e9229873ab1529dda3e0698f753f94a5883b821e5bd3c124bdbdbf16472889ba32ffb02513aca4bec4a738a645729d14a6940a4bf9ff69034409

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
